### PR TITLE
Register plug-in as Packer integration

### PR DESCRIPTION
**Pull request by nywilken**
:wave: fellow Packer maintainer working on migrating your plugin to the Packer integration framework.

This change takes the necessary steps to register this plugin as an official Packer integration.
Integrations can be found on the Packer integration portal at https://developer.hashicorp.com/packer/integrations.

---

The pull-request consists of the following changes:

- Adds controlling, metadata file, `metadata.hcl` for registering the plug-in and it components as integrations.
Details on the contents, along with a description of the attributes, can be found at https://github.com/hashicorp/integration-template.
- Adds the GitHub action workflows for triggering manual and automatic integration updates.
- Restructures the plug-in documentation to match the expected format of the integration framework.
- Adds a `.web-docs` directory for serving the fully render documentation as the integration docs.
- Adds the build-docs make target `make build-docs` for syncing changes to the `docs` directory to the `.web-docs` directory.

Changes to the integration docs can be made at plugin release via the `notify-integration-release-via-tag` workflow or
manually by running the `notify-integration-release-via-manual` workflow.

Details on how the Integration framework pipeline works can be found at https://github.com/hashicorp/packer/pull/12702

### TODOs
- [x] Open pull-request against external plugin.
- [ ] Update integration description [`.web-docs/metadata.hcl`](.web-docs/metadata.hcl).
- [ ] Packer team open internal pull-request to enable integration.
- [ ] Review plugin integration on Packer integration portal .... Iterate

### CODE REVIEW

**Review by Codelax — COMMENTED** [review]
Hello, thanks for this PR and your work on packer

**Review by Codelax — APPROVED** [review]

**Comment by nywilken** [comment]
Hi @Codelax apologies for the delayed response the majority of the team was away for holidays. 

Thank you for merging in this change. We went ahead and enabled the integration on our end. To publish the new integration could you please trigger a manual notification release job for the current version of the Scaleway plug-in.

**Comment by Codelax** [comment]
Thanks for the followup @nywilken 
The manual job just ran, when will we see the changes on packer website ?

**Comment by nywilken** [comment]
> Thanks for the followup @nywilken The manual job just ran, when will we see the changes on packer website ?

Thank you. The integration is now live at https://developer.hashicorp.com/packer/integrations/scaleway/scaleway

If you are still seeing the old plugin docs you may need to hard refresh your browser to flush the cache. This change now enables you to have versioned docs for your plugin and can be updated at your convenience using the provided actions.

**Pull request merged**
